Documents/Models/Document1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document1
    {
        public int id { get; set; }
        public System.DateTime Дата { get; set; }
        public string Направление { get; set; }
        public string Наименование_корсчета { get; set; }
        public string Валюта { get; set; }
        public string Наименование_клиента { get; set; }
        public decimal Сумма { get; set; }
        public string Комментарий { get; set; }
        public string Статус { get; set; }
    }
}

Documents/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documents.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DHEntities : DbContext
    {
        public DHEntities()
            : base("name=DHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document1> Document1 { get; set; }
    }
}

Documents/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Alexey\Git\Crud\documents\Documents\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Documents/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Documents/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Documents.Models;

namespace Documents.Controllers
{
    public class DocumentController : Controller
    {
        DHEntities db = new DHEntities();

        // GET: Document
        public ActionResult Index()
        {
            return View(db.Document1.ToList());
        }

        // GET: Document/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document1 document = db.Document1.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // GET: Document/Create
        public ActionResult Create()
        {
            Document1 model = new Document1();
            model.Дата = DateTime.Now;
            //ViewBag.DateToday = DateTime.Today;
            return this.View(model);
        }

        // POST: Document/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Дата,Направление,Наименование_корсчета,Валюта,Наименование_клиента,Сумма,Комментарий,Статус")] Document1 document)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Document1.Add(document);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Невозможно сохранить изменения. Проверьте данные еще раз");
            }
            return View(document);
            }

        // GET: Document/Edit/5
            public ActionResult Edit(int id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Document1 document = db.Document1.Find(id);
                if (document == null)
                {
                    return HttpNotFound();
                }
            return View(document);
            // return RedirectToAction("Index");
        }

        // POST: Document/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Дата,Направление,Наименование_корсчета,Валюта,Наименование_клиента,Сумма,Комментарий,Статус")] Document1 document)
        {
            if (ModelState.IsValid)
            {
                db.Entry(document).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(document);
        }

        // GET: Document/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document1 document = db.Document1.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: Document/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Document1 document = db.Document1.Find(id);
            db.Document1.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
//вот время это не нашел как убрать. И сразу текущую дату вбить

Documents/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Documents.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Documents/Views/Document/Create.cshtml
@model Documents.Models.Document1

@{
    ViewBag.Title = "Создать";
}

<h2>Создание документа</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

   
    <div class="form-group">
        @Html.LabelFor(model => model.Дата, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Дата, new {type = "date", @Value = Model.Дата.ToString("yyyy-MM-dd") })
            @Html.ValidationMessageFor(model => model.Дата, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Направление, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Направление", new SelectList(new string[] { "Списание", "Поступление" }))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Наименование_корсчета, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Наименование_корсчета", new SelectList(new string[] { "Корсчет ЦБ", "Корсчет СБЕРБАНК", "Корсчет ЛАНТАБАНК" }))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Валюта, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Валюта", new SelectList(new string[] { "RUB", "USD", "EURO" }))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Наименование_клиента, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Наименование_клиента, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Наименование_клиента, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Сумма, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Сумма, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Сумма, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Комментарий, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Комментарий, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Комментарий, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Статус, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Статус, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Статус, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Создать" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Обратно к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/Views/Document/Delete.cshtml
@model Documents.Models.Document1

@{
    ViewBag.Title = "Удалить";
}

<h2>Удалить этот документ?</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Направление)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Направление)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Наименование_корсчета)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование_корсчета)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Валюта)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Валюта)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Наименование_клиента)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование_клиента)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Сумма)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Сумма)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Комментарий)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Комментарий)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Статус)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Статус)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Обратно к списку", "Index")
        </div>
    }
</div>

Documents/Views/Document/Details.cshtml
@model Documents.Models.Document1

@{
    ViewBag.Title = "Детали";
}

<h2>Детали документа</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Направление)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Направление)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Наименование_корсчета)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование_корсчета)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Валюта)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Валюта)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Наименование_клиента)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Наименование_клиента)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Сумма)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Сумма)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Комментарий)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Комментарий)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Статус)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Статус)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Обратно к списку", "Index")
</p>

Documents/Views/Document/Edit.cshtml
@model Documents.Models.Document1

@{
    ViewBag.Title = "Редактировать";
}

<h2>Редактирование документа</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.Дата, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Дата, new { type = "datetime-local" })
            @Html.ValidationMessageFor(model => model.Дата, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Направление, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Направление", new SelectList(new string[] { "Списание", "Поступление" }))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Наименование_корсчета, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Наименование_корсчета", new SelectList(new string[] { "Корсчет ЦБ", "Корсчет СБЕРБАНК", "Корсчет ЛАНТАБАНК" }))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Валюта, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Валюта", new SelectList(new string[] { "RUB", "USD", "EURO" }))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Наименование_клиента, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Наименование_клиента, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Наименование_клиента, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Сумма, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Сумма, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Сумма, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Комментарий, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Комментарий, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Комментарий, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Статус, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Статус, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Статус, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Обратно к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/Views/Document/Index.cshtml
@model IEnumerable<Documents.Models.Document1>

@{
    ViewBag.Title = "Документы";
}

<h2>Документы</h2>

<h3>
    @Html.ActionLink("Создать новый", "Create")
</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Дата)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Направление)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Наименование_корсчета)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Валюта)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Наименование_клиента)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Сумма)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Комментарий)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Статус)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Дата)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Направление)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Наименование_корсчета)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Валюта)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Наименование_клиента)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Сумма)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Комментарий)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Статус)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id = item.id }) |
            @Html.ActionLink("Детали", "Details", new { id = item.id }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>

Documents/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Домашняя страница";
}

<div class="jumbotron">
    <h1>Добавление документов</h1>
    <p class="lead">С помощью этого приложения можно добавлять документы в программу монитор</p>
</div>

<div class="row">

</div>

Documents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Документы</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Домашняя страница", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Документы", "Index", "Document")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Документы</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>